#!/usr/bin/env python3
from __future__ import annotations

import argparse
import difflib
import json
import re
import sys
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SOURCE = ROOT / "contracts/openapi/apgic-v1.yaml"
DEFAULT_TARGET = ROOT / "packages/contracts/src/generated/apgic-v1.ts"
HTTP_METHODS = {"get", "post", "put", "patch", "delete", "options", "head", "trace"}
IDENTIFIER = re.compile(r"^[A-Za-z_$][A-Za-z0-9_$]*$")


class ContractGenerationError(ValueError):
    pass


def ref_name(ref: str) -> str:
    prefix = "#/components/schemas/"
    if not ref.startswith(prefix):
        raise ContractGenerationError(f"unsupported external reference: {ref}")
    name = ref[len(prefix):]
    if not IDENTIFIER.fullmatch(name):
        raise ContractGenerationError(f"invalid schema reference name: {name!r}")
    return name


def property_name(name: str) -> str:
    if IDENTIFIER.fullmatch(name):
        return name
    return json.dumps(name, ensure_ascii=False)


def ts_type(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return ref_name(str(schema["$ref"]))

    enum = schema.get("enum")
    if enum is not None:
        if not isinstance(enum, list) or not enum:
            raise ContractGenerationError("enum must be a non-empty list")
        return " | ".join(json.dumps(value, ensure_ascii=False) for value in enum)

    schema_type = schema.get("type")
    if schema_type == "string":
        return "string"
    if schema_type == "boolean":
        return "boolean"
    if schema_type in {"integer", "number"}:
        return "number"
    if schema_type == "array":
        items = schema.get("items")
        if not isinstance(items, dict):
            raise ContractGenerationError("array schema requires object items")
        return f"Array<{ts_type(items)}>"
    if schema_type == "object":
        properties = schema.get("properties")
        if not properties:
            return "Record<string, unknown>"
        if not isinstance(properties, dict):
            raise ContractGenerationError("object properties must be a mapping")
        required = set(schema.get("required") or [])
        fields: list[str] = []
        for name in sorted(properties):
            child = properties[name]
            if not isinstance(child, dict):
                raise ContractGenerationError(f"property {name!r} schema must be a mapping")
            optional = "" if name in required else "?"
            fields.append(f"{property_name(name)}{optional}: {ts_type(child)}")
        return "{ " + "; ".join(fields) + " }"

    raise ContractGenerationError(f"unsupported schema: {schema!r}")


def operation_ids(document: dict[str, Any]) -> list[str]:
    found: list[str] = []
    for path in sorted((document.get("paths") or {})):
        path_item = document["paths"][path]
        if not isinstance(path_item, dict):
            raise ContractGenerationError(f"path item {path!r} must be a mapping")
        for method in sorted(path_item):
            if method.lower() not in HTTP_METHODS:
                continue
            operation = path_item[method]
            if not isinstance(operation, dict):
                raise ContractGenerationError(f"{method.upper()} {path} must be a mapping")
            operation_id = operation.get("operationId")
            if not isinstance(operation_id, str) or not IDENTIFIER.fullmatch(operation_id):
                raise ContractGenerationError(f"{method.upper()} {path} requires a valid operationId")
            found.append(operation_id)
    if len(found) != len(set(found)):
        raise ContractGenerationError("duplicate operationId detected")
    if not found:
        raise ContractGenerationError("OpenAPI contract has no operations")
    return sorted(found)


def render_contract(document: dict[str, Any]) -> str:
    info = document.get("info") or {}
    version = info.get("version")
    if not isinstance(version, str) or not version.strip():
        raise ContractGenerationError("info.version is required")

    components = document.get("components") or {}
    schemas = components.get("schemas")
    if not isinstance(schemas, dict) or not schemas:
        raise ContractGenerationError("components.schemas must be a non-empty mapping")

    lines = [
        "// Code generated by tools/generate_client_contract.py from contracts/openapi/apgic-v1.yaml.",
        "// DO NOT EDIT.",
        f"export const apiContractVersion = {json.dumps(version)} as const;",
        "",
        "export type ApiOperationId = "
        + " | ".join(json.dumps(value) for value in operation_ids(document))
        + ";",
        "",
    ]

    for name in sorted(schemas):
        if not IDENTIFIER.fullmatch(name):
            raise ContractGenerationError(f"invalid schema name: {name!r}")
        schema = schemas[name]
        if not isinstance(schema, dict):
            raise ContractGenerationError(f"schema {name!r} must be a mapping")

        if schema.get("type") == "object" and "enum" not in schema:
            properties = schema.get("properties") or {}
            if not isinstance(properties, dict):
                raise ContractGenerationError(f"schema {name!r} properties must be a mapping")
            required = set(schema.get("required") or [])
            lines.append(f"export interface {name} {{")
            for property_key in sorted(properties):
                child = properties[property_key]
                if not isinstance(child, dict):
                    raise ContractGenerationError(
                        f"schema {name!r} property {property_key!r} must be a mapping"
                    )
                optional = "" if property_key in required else "?"
                lines.append(
                    f"  {property_name(property_key)}{optional}: {ts_type(child)};"
                )
            lines.append("}")
        else:
            lines.append(f"export type {name} = {ts_type(schema)};")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def load_document(source: Path) -> dict[str, Any]:
    document = yaml.safe_load(source.read_text(encoding="utf-8"))
    if not isinstance(document, dict):
        raise ContractGenerationError("OpenAPI root must be a mapping")
    return document


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", default=str(DEFAULT_SOURCE))
    parser.add_argument("--target", default=str(DEFAULT_TARGET))
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    source = Path(args.source).resolve()
    target = Path(args.target).resolve()
    try:
        expected = render_contract(load_document(source))
    except (OSError, yaml.YAMLError, ContractGenerationError) as exc:
        print(f"CLIENT CONTRACT GENERATION: FAIL: {exc}", file=sys.stderr)
        raise SystemExit(1)

    if args.check:
        if not target.is_file():
            print(f"CLIENT CONTRACT GENERATION: FAIL: missing {target}", file=sys.stderr)
            raise SystemExit(1)
        actual = target.read_text(encoding="utf-8")
        if actual != expected:
            print("CLIENT CONTRACT GENERATION: FAIL: generated client is stale", file=sys.stderr)
            sys.stderr.writelines(
                difflib.unified_diff(
                    actual.splitlines(keepends=True),
                    expected.splitlines(keepends=True),
                    fromfile=str(target),
                    tofile="expected",
                )
            )
            raise SystemExit(1)
        print("CLIENT CONTRACT GENERATION: PASS")
        return

    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(expected, encoding="utf-8")
    print(f"CLIENT CONTRACT GENERATION: WROTE {target}")


if __name__ == "__main__":
    main()
